name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and test CDK Typescript stack
    runs-on: ubuntu-latest
    steps:

      - name: Initiated by user
        run: echo $GITHUB_ACTOR

      - name: Checkout code
        uses: actions/checkout@v3.1.0

      - name: Setup node.js
        uses: actions/setup-node@v3.5.0
      
      - name: Install app dependencies
        run: yarn bundle
      
      - name: Run app unit test
        run: yarn test:app

      - name: Run infra unit test
        run: yarn test:infra
      
      - name: AWS CDK diff
        run: cd infra && npx cdk diff --ci --require-approval never --no-asset-metadata
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"